sugarcube-2:
  macros:
    setBackground:
      name: setBackground
    updatebar:
      name: updatebar
    changemoods:
      name: changemoods
    addmins:
      name: addmins
    playerp:
      name: playerp
    maincomputer:
      name: maincomputer
      container: true
    say:
      name: say
      container: true
    clamps:
      name: clamps
    date:
      name: date
    time24hr:
      name: time24hr
    time12hr:
      name: time12hr
    manageNeeds:
      name: manageNeeds
    creditchange:
      name: creditchange
    debtchange:
      name: debtchange
    autoFabricatorProcess:
      name: autoFabricatorProcess
    blackmarketactivity:
      name: blackmarketactivity
    character:
      name: character
    PlayTrack:
      name: PlayTrack
    displayAreaImage:
      name: displayAreaImage
    setSidebarBackground:
      name: setSidebarBackground
    formatNumber:
      name: formatNumber
    mapWidget:
      name: mapWidget
    koloss:
      name: koloss
    itemchange:
      name: itemchange
    capitalize:
      name: capitalize
    setBackgroundSlide:
      name: setBackgroundSlide
    appearance:
      name: appearance
    ImageDisplay:
      name: ImageDisplay
    on:
      container: true
      children:
        - which
    one:
      container: true
      children:
        - which
    event:
      container: true
      children:
        - which
      deprecated: true
      depecatedSuggestions:
        - on
        - off
    which:
      parents:
        - on
        - off
        - event
    trigger: {}
    off: {}
    live:
      name: live
    l:
      name: l
    lh:
      name: lh
    liveblock:
      name: liveblock
      container: true
    lb:
      name: lb
      container: true
    update:
      name: update
    upd:
      name: upd
    notify:
      name: notify
      container: true
    CreateNPC:
      name: CreateNPC
    AddEventToStack:
      name: AddEventToStack
    fadein:
      name: fadein
      container: true
    fadeout:
      name: fadeout
      container: true
    changerelations:
      name: changerelations
    LowerDeckBusinessStats:
      name: LowerDeckBusinessStats
    LowerDeckBusinessProfitability:
      name: LowerDeckBusinessProfitability
    PrintBusinessEstimates:
      name: PrintBusinessEstimates
    LowerDecksPlayerBusinessActiveStats:
      name: LowerDecksPlayerBusinessActiveStats
    LowerDecksBusinessReport:
      name: LowerDecksBusinessReport
    LowerDecksPlayerBusinessProcessing:
      name: LowerDecksPlayerBusinessProcessing
    ConsumeInputWithChance:
      name: ConsumeInputWithChance
    ProduceOutputWithChance:
      name: ProduceOutputWithChance
    ManageOutputs:
      name: ManageOutputs
    LogEvent:
      name: LogEvent
    ProcessDivisionSale:
      name: ProcessDivisionSale
    ProcessCorporationCycles:
      name: ProcessCorporationCycles
    refresh:
      name: refresh
    CreateCorporation:
      name: CreateCorporation
    CreateDivision:
      name: CreateDivision
    CreateSystem:
      name: CreateSystem

    # Random Event Picker
    RandomEventPicker:
      name: RandomEventPicker
      container: true
    ResetRandomEvent:
      name: ResetRandomEvent
    WipeRandomEventPickerGlobalState:
      name: WipeRandomEventPickerGlobalState
    # Random Event Picker Triggers
    # Empty definition to keep intellisense happy.
    # The macro is only used as a tag and does not do any processing by itself.
    onChangeResetTrigger: {}
    # Random Event Picker Triggers - END
    # Random Event Picker - END